#!/usr/bin/env bash
# The Foundation Package Manager.
# Developed by Brett. (https://github.com/notronaldmcdonald/fpm)
if [ -e $HOME/foundation/foundation-base ]; then
  source $HOME/foundation/foundation-base
else
  echo "Foundation isn't installed properly. Installing for current user..."
  mkdir $HOME/foundation
  curl https://raw.githubusercontent.com/notronaldmcdonald/bash-scripts/master/foundation/foundation-base -o $HOME/foundation/foundation-base
  curl https://raw.githubusercontent.com/notronaldmcdonald/bash-scripts/master/foundation/foundation-extra -o $HOME/foundation/foundation-extra
fi
if [ ! -e $store/.install ]; then
  mkdir  $store/.install
else
  echo "nothing" > /dev/null
fi
if [ -e ~/.fpkgr ]; then
  source ~/.fpkgr/fpkgr
else
  mkdir ~/.fpkgr
  curl -fs https://raw.githubusercontent.com/notronaldmcdonald/bash-scripts/master/foundation/fpkgr/exfpkgr -o ~/.fpkgr/fpkgr
  source ~/.fpkgr/fpkgr
fi
if [ ! -e ~/.fpm ]; then
  mkdir ~/.fpm
else
  echo "nothing" > /dev/null
fi

function search() {
  echo "Searching for package $query in main."
  echo
  curl -fs https://raw.githubusercontent.com/notronaldmcdonald/fpm/core/pkgs/pkglist.txt -o $store/pkglist.tmp
  cat $store/pkglist.tmp | grep $query > $store/output.tmp
  if [ "$(cat $store/output.tmp)" = "" ]; then
    echo "------------------------"
    echo "No results found. Sorry."
    echo "------------------------"
  else
    echo "-----------------------"
    echo "Found $query in main."
    echo "-----------------------"
  fi
  rm -f $store/*.tmp
}

while getopts i:u:s:v:N:c flag
do
  case "${flag}" in
    i) request=${OPTARG} && fpkg-install;;
    u) request=${OPTARG} && fpkg-remove;;
    s) query=${OPTARG} && search;;
    v) curl -fs https://raw.githubusercontent.com/notronaldmcdonald/fpm/core/release-info -o ~/.fpm/release && cat ~/.fpm/release;;
    N) echo "Nuke is not available.";;
    c) echo "Constructor is not available.";;
  esac
done
